### ISSUE TITLE
Actions not converted correctly using PettingZooParallelWrapper

### ISSUE THREAD

**Issue by comet834** [cage-challenge/CybORG#12]
Using `PettingZooParallelWrapper`, actions are not converted from (gym) integers into CybORG actions. Therefore all actions end up as `InvalidActions` (since `int` isn't a valid action class). This could be fixed with some extra logic in the wrapper that instantiates the CybORG actions before calling `self.env.parallel_step`.

**Comment by MitchellKiely** [comment]
Thank you for identify this issue. It has been fixed in the most recent commit.
