### ISSUE TITLE
`typing` syntax error

### ISSUE THREAD

**Issue by rademacher-p** [cage-challenge/CybORG#13]
I'm using Python 3.9 (apparently supported), but I'm seeing some syntax errors in the package for `typing`. Specifically,
```
def step(self, action: Union[int, List[int]] = None) -> (object, float, bool, dict):
```
throws an error,
```
Tuple expression not allowed in type annotation
  Use Tuple[T1, ..., Tn] to indicate a tuple type or Union[T1, T2] to indicate a union type
```

This error seems consistent with the Python [docs](https://docs.python.org/3.9/library/typing.html?highlight=typing#module-typing). Not sure if that syntax for tuple-types was supported in a previous Python version or not...

**Comment by maxstanden** [comment]
The most recent push should have corrected this. Please let us know if you encounter any further bugs with this typing issue as we had some difficulty replicating it on Python 3.9
