### ISSUE TITLE
AllowTraffic incorrect behaviour

### ISSUE THREAD

**Issue by comet834** [cage-challenge/CybORG#14]
In the `AllowTraffic` action in `ControlTraffic.py`, if there is an attempt to allow traffic from a target IP but the host does not currently block _any_ IPs (including the target), then the target IP is blocked. I believe that this is incorrect behaviour? If so, I think a fix would be to remove lines 45 and 46 of `ControlTraffic.py`. Many thanks.

**Comment by maxstanden** [comment]
Thank you for raising this issue. The most recent push has corrected this bug.

**Comment by comet834** [comment]
Would you be able to explain how the most recent push has corrected this? I can't see any changes to `ControlTraffic.py` since Sep 30. Thanks!

**Comment by maxstanden** [comment]
Sorry. forgot to push that file in the update. It should be fixed now.
