### ISSUE TITLE
Evaluate agent in emulation mode

### ISSUE THREAD

**Issue by Anth0rx** [cage-challenge/CybORG#15]
When I see it correctly, the scenarios in which the agents train are simulated environments either specified through yaml files or generated through scripts.

Is it possible to evaluate a trained agent in a virtualized emulation environment?

**Comment by maxstanden** [comment]
We're always eager to discuss future challenges and researches directions! However, we are planning on keeping this issues board for specific CybORG related bugs or enhancements. Please feel free to email us at [cage.aco.challenge@gmail.com](mailto:cage.aco.challenge@gmail.com) to discuss further.
