### ISSUE TITLE
Missing rewards when all drones compromised

### ISSUE THREAD

**Issue by jansen-zhang20** [cage-challenge/CybORG#19]
In `evaluation.py`, the calculation of rewards seems to be broken when the episode ends before the full 500 steps (to my understanding, when all drones have been compromised).

It appears that after `break`, the rewards for the steps the episode did run for are returned via `sum(r)` to `total_reward`, but no (negative) reward is added to `r` for the remaining time steps.

**Comment by maxstanden** [comment]
The most recent commit should have fixed this error
