### ISSUE TITLE
Main README: Evaluating agent performance 

### ISSUE THREAD

**Issue by rafvasq** [cage-challenge/CybORG#20]
Regarding the evaluation script, the main README suggests:

> The agent under evaluation is defined on line 35. 
> To evaluate an agent, extend the [BaseAgent](CybORG/Agents/SimpleAgents/BaseAgent.py). 
> We have included the [RandomAgent](CybORG/Agents/SimpleAgents/RandomAgent.py) as an example of an agent that performs random actions.
> ```
> # Change this line to load your agent
> agents = {agent: RandomAgent() for agent in wrapped_cyborg.possible_agents}
> ```

But [line 35](https://github.com/cage-challenge/CybORG/blob/main/CybORG/Evaluation/evaluation.py#L35) is not that and the evaluation script doesn't seem to include an example of loading an agent.

**Comment by maxstanden** [comment]
The README has been corrected to point at the correct files for evaluation instructions.
