### ISSUE TITLE
Malicious network events flagged for target drone instead of originating drone

### ISSUE THREAD

**Issue by jansen-zhang20** [cage-challenge/CybORG#21]
It appears that malicious network events are being flagged for the *target drone* of an action, rather than the *originating drone* it was sent from. 

Could you confirm that this is intended? It seems counterintuitive and contradicts the documentation ("the number of malicious network events _from_ drone i"). Thanks!

**Example:**
This appears to be due to what you would consider as `local_address` and `remote_address`. 

As an example with `FloodBandwidth`, the below is an example when `FloodBandwidth` is run from host drone `drone_12` to `drone_2`. 
* `hostname` - `drone_12`
* `self.ip_address` - `10.0.78.141`, which is the ip_address for drone 2
* `route` - `['drone_12', 'drone_9', 'drone_4', 'drone_6', 'drone_2']`
>                     event = {
>                         'local_address': self.ip_address,
>                         'remote_port': 8888,
>                         'remote_address': {h_name: ip_addr for ip_addr, h_name in state.ip_addresses.items()}[hostname]
>                     }
* output flagged event to `host.events['NetworkConnections']` -  `[{'local_address': IPv4Address('10.0.78.141'), 'remote_port': 8888, 'remote_address': IPv4Address('10.0.78.142')}]`
>                     # add flagged messages
>                     for i, ip in enumerate(self.ip_addresses):
>                         new_obs[index + i] = 1 if ip in [network_conn['local_address']
>                                                          for interface in obs[own_host_name]['Interface']
>                                                          if 'NetworkConnections' in interface
>                                                          for network_conn in interface['NetworkConnections']] \
>                             else 0
>                     index += len(self.ip_addresses)
* `local_address` is then used to identify the drone to "add flagged messages" in `PettingZooParallelWrapper.py`, therefore returning the target drone rather than the originating drone.

**Comment by maxstanden** [comment]
The most recent update should have fixed this issue
