### ISSUE TITLE
SendData actions return Observation(False) when any drone is red

### ISSUE THREAD

**Issue by jansen-zhang20** [cage-challenge/CybORG#22]
The SendData actions appear to return `Observation(False)` when _any of all 18 agents_ are red, rather than when any agent _on the route_ is red. 

This results in scores of -18 in every step, as soon as red team takes an agent.

This seems to be caused by the check for red agents looping through `host_agents`, which contains all agents rather than just agents on the route. The fix should be to correct `for agent in host_agents:`.

>             for other_hostname in route:
>                 # Get host object for corresponding hostname
>                 host = state.hosts[other_hostname]
>                 # Get the list of agents mapped to sessions for the host
>                 host_agents = host.sessions.keys()
>                 # Iterate through list of agents operating session
>                 for agent in host_agents:
>                     # Check that agent's team name contains 'red', assume modification if true
>                     if 'red' in agent.lower():
>                         # Iterate through list of session objects under agent
>                         for session in state.sessions[agent].values():
>                             # Check if agent has escalated privileges within session
>                             if session.username == 'root' or session.username == 'SYSTEM':
>                                 return obs

**Comment by maxstanden** [comment]
This bug has been fixed in the most recent update.
