### ISSUE TITLE
[bug]true_obs_to_table:KeyError 

### ISSUE THREAD

**Issue by tangyunlong** [cage-challenge/CybORG#39]
I run the following code with reference to the 4th tutorial debug:
from CybORG.Agents.Wrappers.TrueTableWrapper import true_obs_to_table

true_table = true_obs_to_table(true_state,env)
print(true_table)

The error is as follows:
[1](vscode-notebook-cell://ssh-remote%2B192.168.1.242/home/tangyunlong/pettingzooAndOrg/pettingzooTutorial/04_ORGTest_Debug.ipynb#W3sdnNjb2RlLXJlbW90ZQ%3D%3D?line=0) from CybORG.Agents.Wrappers.TrueTableWrapper import true_obs_to_table
----> [3](vscode-notebook-cell://ssh-remote%2B192.168.1.242/home/tangyunlong/pettingzooAndOrg/pettingzooTutorial/04_ORGTest_Debug.ipynb#W3sdnNjb2RlLXJlbW90ZQ%3D%3D?line=2) true_table = true_obs_to_table(true_state,env)
      [4](vscode-notebook-cell://ssh-remote%2B192.168.1.242/home/tangyunlong/pettingzooAndOrg/pettingzooTutorial/04_ORGTest_Debug.ipynb#W3sdnNjb2RlLXJlbW90ZQ%3D%3D?line=3) print(true_table)

File [~/pettingzooAndOrg/cage-challenge-3/CybORG/CybORG/Agents/Wrappers/TrueTableWrapper.py:118](https://vscode-remote+ssh-002dremote-002b192-002e168-002e1-002e242.vscode-resource.vscode-cdn.net/home/tangyunlong/pettingzooAndOrg/pettingzooTutorial/~/pettingzooAndOrg/cage-challenge-3/CybORG/CybORG/Agents/Wrappers/TrueTableWrapper.py:118), in true_obs_to_table(true_obs, env)
    116 wrapper = TrueTableWrapper(env,observer_mode=False)
    117 wrapper.step_counter = 1
--> 118 return wrapper.observation_change(agent=None, observation=true_obs)

File [~/pettingzooAndOrg/cage-challenge-3/CybORG/CybORG/Agents/Wrappers/TrueTableWrapper.py:26](https://vscode-remote+ssh-002dremote-002b192-002e168-002e1-002e242.vscode-resource.vscode-cdn.net/home/tangyunlong/pettingzooAndOrg/pettingzooTutorial/~/pettingzooAndOrg/cage-challenge-3/CybORG/CybORG/Agents/Wrappers/TrueTableWrapper.py:26), in TrueTableWrapper.observation_change(self, agent, observation)
     23 self.step_counter +=1
     24 self._update_scanned()
---> 26 return observation if self.observer_mode else self._create_true_table()

File [~/pettingzooAndOrg/cage-challenge-3/CybORG/CybORG/Agents/Wrappers/TrueTableWrapper.py:68](https://vscode-remote+ssh-002dremote-002b192-002e168-002e1-002e242.vscode-resource.vscode-cdn.net/home/tangyunlong/pettingzooAndOrg/pettingzooTutorial/~/pettingzooAndOrg/cage-challenge-3/CybORG/CybORG/Agents/Wrappers/TrueTableWrapper.py:68), in TrueTableWrapper._create_true_table(self)
     66 hostname = host['System info']['Hostname']
     67 action_space = self.get_action_space(agent = 'Red')
---> 68 known = action_space['ip_address'][ip]
     69 scanned = True if str(ip) in self.scanned_ips else False
     70 access = self._determine_red_access(host['Sessions'])

KeyError: IPv4Address('10.0.214.136')

I don't know what this ‘key error’ stands for and how to fix it

**Comment by djbow2** [comment]
Note this wrapper is no longer supported.

Is it possible the environment was reset before calling this method? The stated ip address is not in the action_space, which indicates this may be the case?

**Comment by tangyunlong** [comment]
Thanks a lot，I would consider using using the pettingzoo wrapper to bypass this issue.
