### ISSUE TITLE
State of emulator.

### ISSUE THREAD

**Issue by kasanari** [cage-challenge/CybORG#42]
The paper that presented Cyborg states that it contains both a simulator and emulator. This is a statement that has been propagated in related work, such as [this recent paper](https://arxiv.org/pdf/2310.13565.pdf). The emulator has to my knowledge not been publicly released.

According to the authors of [this paper](https://arxiv.org/pdf/2305.17246.pdf), they have through written correspondence with the developers of Cyborg received information that development of the emulator is not active, or abandoned.

Could someone confirm this claim?

**Comment by cage-challenge** [comment]
We can confirm that the emulator is not being worked on, and will likely not be published.
