### ISSUE TITLE
Communication wrappers not working

### ISSUE THREAD

**Issue by daveyj678** [cage-challenge/CybORG#5]
When using a communication wrapper (ActionComms/ObsComms), both fail to initialise. They call
```
super(ObsCommsPettingZooParallelWrapper, self).__init__(env, max_steps)
```
however, the init function for their parent class (PettingZooParallelWrapper) takes only env as an argument.

**Comment by maxstanden** [comment]
I believe this issue has been fixed in the most recent commit.

**Comment by daveyj678** [comment]
That's great, thank you
