### ISSUE TITLE
Pettingzoo wrapper for observation change broken

### ISSUE THREAD

**Issue by daveyj678** [cage-challenge/CybORG#8]
There are a few issues with the observation_change() function in the PettingZooParallelWrapper.py file.

1. When adding the blocked IPs to the observation `new_obs[index + i] = 1 if ...` on line 228, the if statement checks for the  ip_addresses in the list, however the list comprehension returns a list containing a list containing the IP addresses. The if statement only checks the elements of the outer list, and thus never finds an IP address in there. Therefore blocked IPs never show up in an agents observation as the conditional fails.

2. Adding flagged malicious processes to the observation rewrites over the first n_drones elements of the observation tensor, as the indexing on line 239 is incorrect. Instead of `new_obs[i] = 1 if ...`, it should read `new_obs[index + i]`.

3. The conditional for checking if there are flagged processes also fails in the same way as point (1), the list of lists issue rather than list of IP addresses.

4. Issue (2) was hiding an issue with the success value on line 222 `new_obs[index] = obs['success'].value`. The `obs['success'].value` can return values from range [0-3], however this violates the observation space constraints (value too high) which are checked on line 275 `assert self._observation_spaces[agent].contains( .... `. This was being hidden as issues (2) and (3) were always writing a 0 at the 0 index, thus the value was never too high for that index of the observation space.

I've got some code to fix issues 1-3 that I can make a PR for, though I'm unsure about how you'd like to fix issue 4, and my fixes for 1-3 will mean that the function always fails on line 275.

**Comment by MitchellKiely** [comment]
Thanks for identifying this issue. The recent commit has the changes that fix this issue.
